[project]
name = "agent-news-alert"
version = "0.1.0"
description = "AI Agent-based workflow to automatically pick out news and send news alert to emails."
authors = [
    {name = "tigerding",email = "zhiyuanding01@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "ipykernel (>=6.29.5,<7.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "markdownify (>=0.14.1,<0.15.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "langchain-openai (>=0.3.1,<0.4.0)",
    "langchain (>=0.3.15,<0.4.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
package-mode = false